// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Policlinic_.Net_Core_;

namespace Policlinic_.Net_Core_.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20211208211435_2")]
    partial class _2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Policlinic_.Net_Core_.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Full_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Passport_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Policlinic_Id")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Policlinic_Id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Policlinic_.Net_Core_.Policlinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Policlinics");
                });

            modelBuilder.Entity("Policlinic_.Net_Core_.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Doctor_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Doctor_Id");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("Policlinic_.Net_Core_.Doctor", b =>
                {
                    b.HasOne("Policlinic_.Net_Core_.Policlinic", "Policlinic")
                        .WithMany()
                        .HasForeignKey("Policlinic_Id");

                    b.Navigation("Policlinic");
                });

            modelBuilder.Entity("Policlinic_.Net_Core_.Procedure", b =>
                {
                    b.HasOne("Policlinic_.Net_Core_.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("Doctor_Id");

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
